name: "Notify Slack on Failure"
description: "Send a Slack notification when a job fails"

inputs:
  slackWebhook:
    description: "Slack webhook URL"
    required: true
  title:
    description: "Notification title"
    required: true
  message:
    description: "Notification message"
    required: true
  channel:
    description: "Slack channel"
    required: false
    default: "#ntf_gh_private-lab"

runs:
  using: "composite"
  steps:
    - name: Notify Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ${{ inputs.channel }}
        SLACK_COLOR: danger
        SLACK_TITLE: ${{ inputs.title }}
        SLACK_MESSAGE: ${{ inputs.message }}
        SLACK_USERNAME: github-bot
        SLACK_ICON_EMOJI: ":x:"
        SLACK_WEBHOOK: ${{ inputs.slackWebhook }}
