---
name: Setup Node.js
description: Setup pnpm, Node.js, and install dependencies

inputs:
  working-directory:
    description: Working directory for pnpm install
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v2

    - name: Install tools with mise
      shell: bash
      run: |
        mise trust 2>/dev/null || true
        mise install

    - name: Get Node.js version from mise.toml
      id: node-version
      shell: bash
      run: |
        NODE_VERSION=$(grep '^node = ' .mise.toml | sed 's/node = "\(.*\)"/\1/')
        echo "version=$NODE_VERSION" >> $GITHUB_OUTPUT

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ steps.node-version.outputs.version }}
        cache: pnpm

    - name: Cache Turborepo
      uses: actions/cache@v5
      with:
        path: .turbo
        key: turbo-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm install --frozen-lockfile
