---
name: 'Bug Report (en)'
description: 'File a bug report (en)'
labels: ['bug']
body:
  - type: 'markdown'
    attributes:
      value: |
        Thanks for creating an issue 😄!
        Please search open/closed issues before submitting. Someone
        might have asked the same thing before 😉!

  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      description: 'A brief description of the issue.'
      placeholder: |
        When I \_**\_, I expected \_\_** to happen but \_\_\_\_ happened instead.
    validations:
      required: true

  - type: 'input'
    id: 'browser'
    attributes:
      label: 'Browser'
      description: 'The browser(s) this issue occurred with.'
      placeholder: 'Google Chrome 93'

  - type: 'checkboxes'
    id: 'operating-system'
    attributes:
      label: 'Operating System'
      description: 'The operating system(s) this issue occurred with.'
      options:
        - label: 'macOS'
        - label: 'Windows'
        - label: 'Linux'

  - type: 'textarea'
    id: 'additional-information'
    attributes:
      label: 'Additional Information'
      description: |
        Use this section to provide any additional information you might have
        like screenshots, notes, or links to ideas.
