---
name: 'Feature Request (jp)'
description: '機能または拡張機能をリクエストする'
labels: ['needs triage']
body:
  - type: 'markdown'
    attributes:
      value: |
        問題を提出していただきありがとうございます 😄!
        送信する前に、未解決/終了済みの問題を検索してください。誰か
        前にも同じことを質問したかもしれません 😉!

  - type: 'textarea'
    id: 'description'
    attributes:
      label: '詳細'
      description: 'リクエストを 1 文または 2 文で説明してください。'
    validations:
      required: true

  - type: 'textarea'
    id: 'alternatives'
    attributes:
      label: '代替案'
      description: |
        これを作成する前に代替ソリューションを検討しましたか？

  - type: 'textarea'
    id: 'additional-information'
    attributes:
      label: '追加情報'
      description: |
        この取り組みを支援するためにどのようなリソース (リンク、スクリーンショットなど) が必要ですか?
